# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: This could be a linter
      run: |
        docker pull ceph/daemon-base:latest-nautilus
        echo but it is not.

  word-rules:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       word:
       - "wibble"
       - "flan"
       - "batman"

   steps:
   - uses: actions/checkout@v2
   - name: I dislike the word "wibble"
     run: |
      bash -c '! grep -q "${{ matrix.word }}" README.md'
